Traceback (most recent call last):
  File "train.py", line 437, in <module>
    train(data_dir, model_dir, args)
  File "train.py", line 246, in train
    loss_gender.backward()
  File "/opt/conda/lib/python3.8/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 125, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.